package constants

var ENV = []string{
	"SERVER_PORT",
	"MIGRATE",
	"POSTGRES_PASS",
	"POSTGRES_DB",
	"POSTGRES_HOST",
	"POSTGRES_PORT",
	"REDIS_HOST",
	"REDIS_PORT",
	"JWT_ACCESS_KEY_SECRET",
	"JWT_REFRESH_KEY_SECRET",
}

const (
	DEV_CORS_ALLOWED_ORIGINS  = "*"
	PROD_CORS_ALLOWED_ORIGINS = ""
)
